<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\RecipeIngredient;
use Illuminate\Database\Seeder;

class OfficialRecipeSeeder extends Seeder
{
    public function run(): void
    {
        $recipes = [
            [
                'title'       => 'Arroz Caldo',
                'description' => 'Comforting Filipino rice porridge with ginger, chicken, and toppings. Perfect for rainy days or when you\'re feeling under the weather.',
                'budget_tag'  => 'budget_200',
                'cost'        => 160,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 35,
                'difficulty'  => 'easy',
                'tags'        => ['manok', 'sabaw', 'klasiko'],
                'steps'       => [
                    'Sauté ginger and garlic in oil until fragrant.',
                    'Add chicken pieces and cook until no longer pink.',
                    'Pour in washed rice and stir to coat with the oil.',
                    'Add chicken broth or water (4 cups). Bring to a boil.',
                    'Reduce heat and simmer 25 minutes, stirring occasionally, until porridge is thick.',
                    'Season with fish sauce. Serve topped with green onion, fried garlic, and a squeeze of calamansi.',
                ],
                'ingredients' => [
                    ['name' => 'Chicken (cut small)', 'qty' => '300g',      'price' => 50],
                    ['name' => 'Glutinous rice (malagkit)', 'qty' => '1 cup','price' => 30],
                    ['name' => 'Ginger (luya)',       'qty' => '2 inch knob','price' => 8],
                    ['name' => 'Garlic',              'qty' => '5 cloves',  'price' => 5],
                    ['name' => 'Fish sauce (patis)',  'qty' => '2 tbsp',    'price' => 5],
                    ['name' => 'Green onion',         'qty' => '3 stalks',  'price' => 10],
                    ['name' => 'Calamansi',           'qty' => '4 pcs',     'price' => 8],
                    ['name' => 'Chicken broth or water','qty' => '4 cups',  'price' => 10],
                    ['name' => 'Cooking oil',         'qty' => '2 tbsp',    'price' => 5],
                ],
            ],
            [
                'title'       => 'Nilaga',
                'description' => 'Clear boiled beef soup with potatoes, cabbage, and peppercorns — one of the most beloved everyday Filipino dishes.',
                'budget_tag'  => 'budget_400',
                'cost'        => 380,
                'servings'    => 5,
                'prep'        => 10,
                'cook'        => 90,
                'difficulty'  => 'easy',
                'tags'        => ['baka', 'sabaw', 'klasiko'],
                'steps'       => [
                    'Boil beef with onion and peppercorns in water for about 1 hour until tender.',
                    'Skim off foam and fat from the surface.',
                    'Add potatoes and cook for 10 minutes.',
                    'Add cabbage, fish sauce, and salt. Simmer 5 more minutes.',
                    'Serve hot with rice and patis on the side.',
                ],
                'ingredients' => [
                    ['name' => 'Beef (buto-buto or shank)', 'qty' => '½ kg', 'price' => 250],
                    ['name' => 'Potatoes',           'qty' => '2 pcs',     'price' => 30],
                    ['name' => 'Cabbage',            'qty' => '¼ head',    'price' => 20],
                    ['name' => 'Onion',              'qty' => '1 pc',      'price' => 10],
                    ['name' => 'Peppercorns',        'qty' => '1 tbsp',    'price' => 5],
                    ['name' => 'Fish sauce (patis)', 'qty' => '2 tbsp',    'price' => 5],
                    ['name' => 'Salt',               'qty' => 'to taste',  'price' => 2],
                ],
            ],
            [
                'title'       => 'Pakbet Ilocano',
                'description' => 'Ilocano-style mixed vegetable stew with fermented shrimp paste (bagoong). A proud tradition from the Ilocos region.',
                'budget_tag'  => 'budget_200',
                'cost'        => 180,
                'servings'    => 4,
                'prep'        => 15,
                'cook'        => 20,
                'difficulty'  => 'easy',
                'tags'        => ['gulay', 'klasiko', 'tradisyunal'],
                'steps'       => [
                    'Sauté garlic, onion, and tomatoes in oil.',
                    'Add pork and cook until lightly browned.',
                    'Add all vegetables: ampalaya, eggplant, kalabasa, okra, sitaw.',
                    'Pour in bagoong Ilocano (not alamang) and a little water.',
                    'Cover and simmer 15 minutes without stirring to prevent bitterness from ampalaya.',
                    'Serve hot with steamed rice.',
                ],
                'ingredients' => [
                    ['name' => 'Ampalaya (bitter gourd)', 'qty' => '1 pc', 'price' => 20],
                    ['name' => 'Eggplant (talong)',  'qty' => '2 pcs',     'price' => 20],
                    ['name' => 'Kalabasa',           'qty' => '200g',      'price' => 20],
                    ['name' => 'Okra',               'qty' => '10 pcs',    'price' => 15],
                    ['name' => 'Sitaw',              'qty' => '1 bundle',  'price' => 15],
                    ['name' => 'Pork (sliced)',      'qty' => '150g',      'price' => 50],
                    ['name' => 'Bagoong Ilocano',    'qty' => '3 tbsp',    'price' => 20],
                    ['name' => 'Garlic',             'qty' => '4 cloves',  'price' => 5],
                    ['name' => 'Tomatoes',           'qty' => '2 pcs',     'price' => 15],
                ],
            ],
            [
                'title'       => 'Laing',
                'description' => 'Taro leaves slow-cooked in coconut milk with shrimp paste and chili — a Bicolano classic that\'s rich and deeply flavorful.',
                'budget_tag'  => 'budget_200',
                'cost'        => 195,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 45,
                'difficulty'  => 'easy',
                'tags'        => ['gulay', 'espesyal', 'klasiko'],
                'steps'       => [
                    'Do NOT wash the dried taro leaves — this is essential for proper texture.',
                    'Combine coconut cream, bagoong, garlic, ginger, and chili in a pot.',
                    'Add dried taro leaves on top. Do not stir yet.',
                    'Cook on medium heat for about 15 minutes.',
                    'Once coconut milk starts to thicken, gently fold leaves into the sauce.',
                    'Add pork or shrimp and simmer another 20 minutes until oil separates.',
                    'Serve with rice.',
                ],
                'ingredients' => [
                    ['name' => 'Dried taro leaves (gabi)', 'qty' => '200g', 'price' => 40],
                    ['name' => 'Coconut cream (gata)', 'qty' => '400ml',   'price' => 60],
                    ['name' => 'Pork or shrimp',      'qty' => '150g',     'price' => 55],
                    ['name' => 'Bagoong alamang',     'qty' => '2 tbsp',   'price' => 20],
                    ['name' => 'Garlic',              'qty' => '5 cloves', 'price' => 5],
                    ['name' => 'Ginger',              'qty' => '1 inch',   'price' => 5],
                    ['name' => 'Siling labuyo',       'qty' => '5 pcs',    'price' => 8],
                ],
            ],
            [
                'title'       => 'Kare-Kare',
                'description' => 'Classic Filipino oxtail and vegetable stew in rich peanut sauce — always served with bagoong alamang on the side.',
                'budget_tag'  => 'budget_600',
                'cost'        => 550,
                'servings'    => 6,
                'prep'        => 20,
                'cook'        => 120,
                'difficulty'  => 'hard',
                'tags'        => ['baka', 'espesyal', 'tradisyunal'],
                'steps'       => [
                    'Boil oxtail in water for 1.5 hours until very tender. Reserve broth.',
                    'Sauté garlic and onion in oil. Add oxtail and cook 3 minutes.',
                    'Pour in the reserved broth. Add peanut butter and achuete water.',
                    'Stir until peanut butter is fully dissolved and sauce is smooth.',
                    'Add banana blossom (puso ng saging), sitaw, and eggplant. Cook 10 minutes.',
                    'Thicken with rice powder if needed. Season with salt.',
                    'Serve with bagoong alamang and steamed rice.',
                ],
                'ingredients' => [
                    ['name' => 'Oxtail (buntot ng baka)', 'qty' => '600g','price' => 320],
                    ['name' => 'Peanut butter',       'qty' => '½ cup',    'price' => 45],
                    ['name' => 'Puso ng saging (banana blossom)', 'qty' => '1 pc', 'price' => 40],
                    ['name' => 'Sitaw',               'qty' => '1 bundle', 'price' => 20],
                    ['name' => 'Eggplant',            'qty' => '2 pcs',    'price' => 20],
                    ['name' => 'Achuete (annatto)',   'qty' => '1 tbsp',   'price' => 8],
                    ['name' => 'Bagoong alamang (for serving)', 'qty' => '¼ cup', 'price' => 30],
                    ['name' => 'Garlic, onion',       'qty' => '1 head, 1 pc', 'price' => 15],
                ],
            ],
            [
                'title'       => 'Chicken Inasal',
                'description' => 'Visayan-style grilled chicken marinated in calamansi, vinegar, and annatto. Best with garlic rice and chicken oil.',
                'budget_tag'  => 'budget_200',
                'cost'        => 190,
                'servings'    => 3,
                'prep'        => 15,
                'cook'        => 30,
                'difficulty'  => 'medium',
                'tags'        => ['manok', 'espesyal', 'tradisyunal'],
                'steps'       => [
                    'Mix calamansi juice, vinegar, garlic, ginger, lemongrass, salt, and sugar for marinade.',
                    'Marinate chicken for at least 2 hours (overnight is best).',
                    'Grill over medium coals, basting with chicken oil (or butter) and achuete every few minutes.',
                    'Grill until skin is charred and chicken is cooked through, about 25 minutes.',
                    'Serve with garlic rice, soy-calamansi dipping sauce, and soup (goto).',
                ],
                'ingredients' => [
                    ['name' => 'Chicken (quarter legs)', 'qty' => '3 pcs',  'price' => 100],
                    ['name' => 'Calamansi juice',     'qty' => '¼ cup',    'price' => 20],
                    ['name' => 'Coconut vinegar',     'qty' => '3 tbsp',   'price' => 10],
                    ['name' => 'Lemongrass (tanglad)','qty' => '2 stalks', 'price' => 8],
                    ['name' => 'Garlic',              'qty' => '5 cloves', 'price' => 5],
                    ['name' => 'Ginger',              'qty' => '1 inch',   'price' => 5],
                    ['name' => 'Achuete powder',      'qty' => '1 tsp',    'price' => 5],
                    ['name' => 'Butter or chicken oil','qty' => '2 tbsp',  'price' => 15],
                    ['name' => 'Salt and sugar',      'qty' => '1 tsp each','price' => 3],
                ],
            ],
            [
                'title'       => 'Pinakbet Tagalog',
                'description' => 'Tagalog-style mixed vegetable dish with bagoong alamang. Lighter than its Ilocano cousin but just as delicious.',
                'budget_tag'  => 'budget_200',
                'cost'        => 165,
                'servings'    => 4,
                'prep'        => 15,
                'cook'        => 20,
                'difficulty'  => 'easy',
                'tags'        => ['gulay', 'klasiko', 'masustansya'],
                'steps'       => [
                    'Sauté garlic, onion, and tomatoes in oil for 3 minutes.',
                    'Add pork and cook until no longer pink.',
                    'Add bagoong alamang and stir.',
                    'Add kalabasa and a splash of water. Cover and cook 5 minutes.',
                    'Add eggplant, sitaw, and okra. Toss gently.',
                    'Cover and steam-cook 10 minutes. Do not overcook.',
                ],
                'ingredients' => [
                    ['name' => 'Kalabasa',           'qty' => '200g',      'price' => 20],
                    ['name' => 'Eggplant',           'qty' => '2 pcs',     'price' => 20],
                    ['name' => 'Sitaw',              'qty' => '1 bundle',  'price' => 15],
                    ['name' => 'Okra',               'qty' => '8 pcs',     'price' => 12],
                    ['name' => 'Pork belly',         'qty' => '150g',      'price' => 55],
                    ['name' => 'Bagoong alamang',    'qty' => '2 tbsp',    'price' => 15],
                    ['name' => 'Garlic, onion, tomatoes', 'qty' => 'as needed', 'price' => 15],
                ],
            ],
            [
                'title'       => 'Pork Menudo',
                'description' => 'Tomato-based pork and liver stew with potatoes, carrots, and raisins. A fiesta staple loved by young and old.',
                'budget_tag'  => 'budget_400',
                'cost'        => 280,
                'servings'    => 5,
                'prep'        => 15,
                'cook'        => 40,
                'difficulty'  => 'medium',
                'tags'        => ['baboy', 'espesyal', 'klasiko'],
                'steps'       => [
                    'Sauté garlic and onion until fragrant.',
                    'Add diced pork and cook until browned.',
                    'Add tomato paste and cook 2 minutes.',
                    'Pour in soy sauce and a cup of water. Simmer 15 minutes.',
                    'Add potatoes and carrots. Cook until tender.',
                    'Add liver, bell pepper, and raisins. Simmer 5 more minutes.',
                    'Season with salt and pepper. Serve with rice.',
                ],
                'ingredients' => [
                    ['name' => 'Pork (cubed)',       'qty' => '300g',      'price' => 100],
                    ['name' => 'Pork liver',         'qty' => '100g',      'price' => 30],
                    ['name' => 'Potatoes (cubed)',   'qty' => '2 pcs',     'price' => 25],
                    ['name' => 'Carrots (cubed)',    'qty' => '1 pc',      'price' => 15],
                    ['name' => 'Tomato paste',       'qty' => '3 tbsp',    'price' => 20],
                    ['name' => 'Red bell pepper',    'qty' => '1 pc',      'price' => 25],
                    ['name' => 'Raisins',            'qty' => '2 tbsp',    'price' => 15],
                    ['name' => 'Soy sauce',          'qty' => '2 tbsp',    'price' => 5],
                    ['name' => 'Garlic, onion',      'qty' => '1 head, 1 pc','price' => 10],
                ],
            ],
            [
                'title'       => 'Dinuguan',
                'description' => 'Savory pork blood stew cooked with vinegar and chili. A bold Pinoy classic that\'s best eaten with puto.',
                'budget_tag'  => 'budget_200',
                'cost'        => 210,
                'servings'    => 5,
                'prep'        => 15,
                'cook'        => 40,
                'difficulty'  => 'medium',
                'tags'        => ['baboy', 'klasiko', 'tradisyunal'],
                'steps'       => [
                    'Sauté garlic, onion, and ginger in oil.',
                    'Add pork and cook until browned. Season with fish sauce.',
                    'Add pig\'s blood and stir constantly while cooking over medium heat.',
                    'Pour in vinegar. Do not stir — let it cook 5 minutes first.',
                    'Add siling haba (long green chili). Season with salt and a pinch of sugar.',
                    'Simmer until sauce thickens. Serve with puto or rice.',
                ],
                'ingredients' => [
                    ['name' => 'Pork (with fat)',    'qty' => '300g',      'price' => 100],
                    ['name' => 'Pig\'s blood',       'qty' => '1 cup',     'price' => 30],
                    ['name' => 'Vinegar',            'qty' => '¼ cup',     'price' => 8],
                    ['name' => 'Siling haba',        'qty' => '3 pcs',     'price' => 10],
                    ['name' => 'Garlic',             'qty' => '5 cloves',  'price' => 5],
                    ['name' => 'Onion',              'qty' => '1 pc',      'price' => 10],
                    ['name' => 'Ginger',             'qty' => '1 inch',    'price' => 5],
                    ['name' => 'Fish sauce, salt, sugar', 'qty' => 'to taste', 'price' => 5],
                ],
            ],
            [
                'title'       => 'Pork Humba',
                'description' => 'Visayan braised pork belly in soy sauce, vinegar, and banana blossom — the southern cousin of adobo with a sweeter twist.',
                'budget_tag'  => 'budget_400',
                'cost'        => 320,
                'servings'    => 5,
                'prep'        => 10,
                'cook'        => 60,
                'difficulty'  => 'easy',
                'tags'        => ['baboy', 'espesyal', 'tradisyunal'],
                'steps'       => [
                    'Brown pork belly in its own fat over medium heat.',
                    'Add garlic, onion, and cook until fragrant.',
                    'Pour in soy sauce, vinegar, and sugar. Stir to combine.',
                    'Add pineapple juice and bay leaves. Bring to a boil.',
                    'Reduce heat and simmer 45 minutes until pork is very tender.',
                    'Add banana blossom and cook 5 more minutes.',
                    'Serve over rice — the sauce is amazing!',
                ],
                'ingredients' => [
                    ['name' => 'Pork belly (liempo)', 'qty' => '½ kg',    'price' => 180],
                    ['name' => 'Soy sauce',           'qty' => '¼ cup',   'price' => 10],
                    ['name' => 'Vinegar',             'qty' => '3 tbsp',  'price' => 8],
                    ['name' => 'Brown sugar',         'qty' => '2 tbsp',  'price' => 8],
                    ['name' => 'Pineapple juice',     'qty' => '½ cup',   'price' => 25],
                    ['name' => 'Banana blossom (puso ng saging)', 'qty' => '1 cup', 'price' => 30],
                    ['name' => 'Garlic, onion, bay leaves', 'qty' => 'as needed', 'price' => 15],
                ],
            ],
        ];

        foreach ($recipes as $data) {
            $recipe = Recipe::create([
                'user_id'           => null,
                'title'             => $data['title'],
                'description'       => $data['description'],
                'source'            => 'official',
                'budget_tag'        => $data['budget_tag'],
                'estimated_cost'    => $data['cost'],
                'servings'          => $data['servings'],
                'prep_time_minutes' => $data['prep'],
                'cook_time_minutes' => $data['cook'],
                'difficulty'        => $data['difficulty'],
                'tags'              => $data['tags'],
                'steps'             => $data['steps'],
                'is_published'      => true,
                'is_premium_only'   => false,
            ]);

            foreach ($data['ingredients'] as $i => $ing) {
                RecipeIngredient::create([
                    'recipe_id'       => $recipe->id,
                    'name'            => $ing['name'],
                    'quantity'        => $ing['qty'],
                    'unit'            => '',
                    'estimated_price' => $ing['price'],
                    'sort_order'      => $i,
                ]);
            }
        }

        $this->command->info('Seeded 10 official uLam recipes.');
    }
}
