<?php

namespace Database\Seeders;

use App\Models\Recipe;
use App\Models\RecipeIngredient;
use App\Models\User;
use Illuminate\Database\Seeder;

class RecipeSeeder extends Seeder
{
    public function run(): void
    {
        $user = User::first();
        if (! $user) {
            $this->command->warn('No users found. Register an account first.');
            return;
        }

        $recipes = [
            [
                'title'       => 'Sinigang na Baboy',
                'description' => 'Classic Filipino sour pork soup with kangkong and radish — the ultimate comfort meal.',
                'budget_tag'  => 'budget_400',
                'cost'        => 320,
                'servings'    => 5,
                'prep'        => 15,
                'cook'        => 45,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['baboy', 'sabaw', 'klasiko'],
                'steps'       => [
                    'Boil pork ribs in water until tender, about 30 minutes.',
                    'Add sampaloc sinigang mix and stir until dissolved.',
                    'Add tomatoes, onion, and radish. Simmer 5 minutes.',
                    'Add sitaw and kangkong last. Cook 2 more minutes.',
                    'Season with fish sauce and serve hot with rice.',
                ],
                'ingredients' => [
                    ['name' => 'Pork ribs',         'qty' => '½ kg',      'price' => 180],
                    ['name' => 'Sinigang sa Sampaloc mix', 'qty' => '1 pack', 'price' => 12],
                    ['name' => 'Kangkong',           'qty' => '1 bundle',  'price' => 20],
                    ['name' => 'Radish (labanos)',   'qty' => '1 pc',      'price' => 15],
                    ['name' => 'Sitaw',              'qty' => '1 bundle',  'price' => 20],
                    ['name' => 'Tomatoes',           'qty' => '3 pcs',     'price' => 20],
                    ['name' => 'Onion',              'qty' => '1 pc',      'price' => 10],
                    ['name' => 'Fish sauce (patis)', 'qty' => 'to taste',  'price' => 5],
                    ['name' => 'Water',              'qty' => '1.5 liters','price' => 0],
                ],
            ],
            [
                'title'       => 'Adobong Manok',
                'description' => 'Tender chicken braised in vinegar, soy sauce, garlic, and bay leaves. The best baon recipe!',
                'budget_tag'  => 'budget_200',
                'cost'        => 190,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 35,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['manok', 'klasiko', 'mabilis'],
                'steps'       => [
                    'Marinate chicken in soy sauce, vinegar, and garlic for 15 minutes.',
                    'Heat oil in pan and sauté garlic until golden.',
                    'Add chicken and brown on all sides.',
                    'Pour in the marinade and bay leaves. Cover and simmer 25 minutes.',
                    'Remove lid and reduce sauce until slightly thick. Serve with rice.',
                ],
                'ingredients' => [
                    ['name' => 'Chicken (cut-up)',  'qty' => '1 kg',     'price' => 130],
                    ['name' => 'Soy sauce (toyo)', 'qty' => '¼ cup',    'price' => 10],
                    ['name' => 'Vinegar',           'qty' => '¼ cup',    'price' => 8],
                    ['name' => 'Garlic',            'qty' => '6 cloves', 'price' => 10],
                    ['name' => 'Bay leaves (dahon ng laurel)', 'qty' => '3 pcs', 'price' => 2],
                    ['name' => 'Peppercorns',       'qty' => '1 tsp',    'price' => 3],
                    ['name' => 'Cooking oil',       'qty' => '2 tbsp',   'price' => 5],
                ],
            ],
            [
                'title'       => 'Ginisang Monggo with Pork',
                'description' => 'Hearty mung bean soup with pork and malunggay — nutritious, filling, and very affordable.',
                'budget_tag'  => 'budget_100',
                'cost'        => 95,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 40,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['gulay', 'sabaw', 'masustansya'],
                'steps'       => [
                    'Boil monggo in water until soft, about 20 minutes.',
                    'In a separate pan, sauté garlic, onion, and tomato.',
                    'Add pork and cook until browned.',
                    'Combine pork with softened monggo and stir.',
                    'Add malunggay and season with fish sauce. Simmer 5 minutes.',
                ],
                'ingredients' => [
                    ['name' => 'Monggo (mung beans)', 'qty' => '1 cup',  'price' => 25],
                    ['name' => 'Pork belly (liempo)', 'qty' => '200g',   'price' => 40],
                    ['name' => 'Malunggay leaves',    'qty' => '1 cup',  'price' => 10],
                    ['name' => 'Tomatoes',            'qty' => '2 pcs',  'price' => 10],
                    ['name' => 'Garlic',              'qty' => '4 cloves','price' => 5],
                    ['name' => 'Onion',               'qty' => '1 pc',   'price' => 8],
                ],
            ],
            [
                'title'       => 'Tortang Talong',
                'description' => 'Grilled eggplant egg omelette — quick, cheap, and delicious. Perfect weekday breakfast.',
                'budget_tag'  => 'budget_100',
                'cost'        => 45,
                'servings'    => 2,
                'prep'        => 10,
                'cook'        => 15,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => false,
                'tags'        => ['gulay', 'itlog', 'prito', 'mabilis'],
                'steps'       => [
                    'Grill or roast eggplant directly on flame until skin is charred.',
                    'Peel the skin off and flatten the eggplant with a fork.',
                    'Beat eggs with salt and pepper. Dip flattened eggplant in egg.',
                    'Fry in hot oil until golden on both sides.',
                    'Serve with rice and banana ketchup.',
                ],
                'ingredients' => [
                    ['name' => 'Talong (eggplant)',  'qty' => '2 large pcs', 'price' => 20],
                    ['name' => 'Eggs',               'qty' => '2 pcs',       'price' => 16],
                    ['name' => 'Salt and pepper',    'qty' => 'to taste',    'price' => 2],
                    ['name' => 'Cooking oil',        'qty' => '2 tbsp',      'price' => 5],
                ],
            ],
            [
                'title'       => 'Bicol Express',
                'description' => 'Spicy pork and coconut cream stew from Bicol region. Goes amazing with garlic fried rice!',
                'budget_tag'  => 'budget_400',
                'cost'        => 360,
                'servings'    => 5,
                'prep'        => 15,
                'cook'        => 40,
                'difficulty'  => 'medium',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['baboy', 'espesyal', 'klasiko'],
                'steps'       => [
                    'Blanch pork in boiling water for 5 minutes and drain.',
                    'Sauté garlic, onion, and ginger in oil.',
                    'Add pork and cook until slightly browned.',
                    'Pour in coconut cream and bring to a simmer.',
                    'Add siling labuyo, bagoong alamang, and salt. Cook 20 minutes until sauce thickens.',
                ],
                'ingredients' => [
                    ['name' => 'Pork belly (liempo)',  'qty' => '½ kg',   'price' => 180],
                    ['name' => 'Coconut cream (gata)', 'qty' => '400ml',  'price' => 60],
                    ['name' => 'Siling labuyo (bird eye chili)', 'qty' => '10 pcs', 'price' => 15],
                    ['name' => 'Bagoong alamang',      'qty' => '2 tbsp', 'price' => 20],
                    ['name' => 'Garlic',               'qty' => '6 cloves','price' => 8],
                    ['name' => 'Onion',                'qty' => '1 pc',   'price' => 10],
                    ['name' => 'Ginger',               'qty' => '1 inch', 'price' => 5],
                ],
            ],
            [
                'title'       => 'Chicken Tinola',
                'description' => 'Light ginger-based chicken soup with green papaya and malunggay — the Filipino feel-good soup.',
                'budget_tag'  => 'budget_200',
                'cost'        => 175,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 30,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['manok', 'sabaw', 'masustansya', 'klasiko'],
                'steps'       => [
                    'Sauté ginger, garlic, and onion in oil until fragrant.',
                    'Add chicken pieces and cook until lightly browned.',
                    'Pour in water or broth and bring to a boil.',
                    'Add green papaya and cook until tender, about 10 minutes.',
                    'Add malunggay leaves and fish sauce. Simmer 2 minutes and serve.',
                ],
                'ingredients' => [
                    ['name' => 'Chicken (cut-up)',    'qty' => '700g',       'price' => 100],
                    ['name' => 'Green papaya (papaya)', 'qty' => '½ pc',   'price' => 20],
                    ['name' => 'Malunggay leaves',    'qty' => '1 cup',      'price' => 10],
                    ['name' => 'Ginger (luya)',       'qty' => '2 inch knob','price' => 8],
                    ['name' => 'Garlic',              'qty' => '4 cloves',   'price' => 5],
                    ['name' => 'Onion',               'qty' => '1 pc',       'price' => 10],
                    ['name' => 'Fish sauce (patis)',  'qty' => '2 tbsp',     'price' => 5],
                ],
            ],
            [
                'title'       => 'Pinangat na Isda',
                'description' => 'Fish cooked in vinegar and ginger — tangy and savory. Uses cheap galunggong or tilapia.',
                'budget_tag'  => 'budget_200',
                'cost'        => 155,
                'servings'    => 3,
                'prep'        => 10,
                'cook'        => 20,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => false,
                'tags'        => ['isda', 'klasiko', 'mabilis'],
                'steps'       => [
                    'Clean and gut the fish. Season with salt and let rest 5 minutes.',
                    'Arrange ginger, garlic, and tomatoes on the bottom of the pan.',
                    'Place fish on top of the aromatics.',
                    'Pour in vinegar and water. Do not stir.',
                    'Cover and cook on medium heat for 15-20 minutes until done.',
                ],
                'ingredients' => [
                    ['name' => 'Galunggong or tilapia', 'qty' => '4 pcs',    'price' => 100],
                    ['name' => 'Vinegar',               'qty' => '¼ cup',    'price' => 8],
                    ['name' => 'Ginger (luya)',         'qty' => '1 inch',   'price' => 5],
                    ['name' => 'Garlic',                'qty' => '4 cloves', 'price' => 5],
                    ['name' => 'Tomatoes',              'qty' => '2 pcs',    'price' => 15],
                    ['name' => 'Salt',                  'qty' => 'to taste', 'price' => 2],
                ],
            ],
            [
                'title'       => 'Ginataang Kalabasa at Sitaw',
                'description' => 'Squash and green beans simmered in rich coconut milk with shrimp. A simple veggie ulam.',
                'budget_tag'  => 'budget_200',
                'cost'        => 145,
                'servings'    => 4,
                'prep'        => 10,
                'cook'        => 20,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['gulay', 'masustansya', 'klasiko'],
                'steps'       => [
                    'Sauté garlic and onion in oil until soft.',
                    'Add shrimp (or pork) and cook for 2 minutes.',
                    'Add kalabasa cubes and coconut milk. Simmer until squash is tender.',
                    'Add sitaw pieces and bagoong. Cook 3 more minutes.',
                    'Season to taste and serve with rice.',
                ],
                'ingredients' => [
                    ['name' => 'Kalabasa (squash)',    'qty' => '300g',  'price' => 25],
                    ['name' => 'Sitaw (string beans)', 'qty' => '1 bundle', 'price' => 20],
                    ['name' => 'Coconut milk (gata)',  'qty' => '1 can', 'price' => 45],
                    ['name' => 'Shrimp (hipon)',       'qty' => '100g',  'price' => 40],
                    ['name' => 'Bagoong alamang',      'qty' => '1 tbsp','price' => 8],
                    ['name' => 'Garlic',               'qty' => '4 cloves','price' => 5],
                    ['name' => 'Onion',                'qty' => '1 pc',  'price' => 10],
                ],
            ],
            [
                'title'       => 'Pork Chopsuey',
                'description' => 'Colorful stir-fried vegetables with pork and quail eggs in oyster sauce. Very budget-friendly!',
                'budget_tag'  => 'budget_400',
                'cost'        => 240,
                'servings'    => 4,
                'prep'        => 15,
                'cook'        => 15,
                'difficulty'  => 'medium',
                'source'      => 'community',
                'published'   => true,
                'tags'        => ['baboy', 'gulay', 'mabilis'],
                'steps'       => [
                    'Blanch cauliflower and carrots in boiling water for 2 minutes.',
                    'Sauté garlic, onion, and pork in oil until pork is cooked.',
                    'Add bell pepper, snow peas, and blanched veggies.',
                    'Pour in oyster sauce, soy sauce, and chicken broth.',
                    'Mix cornstarch with water and add to thicken. Add quail eggs last.',
                ],
                'ingredients' => [
                    ['name' => 'Pork (sliced)',           'qty' => '200g',    'price' => 70],
                    ['name' => 'Cauliflower',             'qty' => '1 small', 'price' => 30],
                    ['name' => 'Carrots',                 'qty' => '1 pc',    'price' => 15],
                    ['name' => 'Bell pepper (red/green)', 'qty' => '1 pc each','price' => 25],
                    ['name' => 'Snow peas (chicharo)',    'qty' => '1 cup',   'price' => 20],
                    ['name' => 'Quail eggs (canned)',     'qty' => '1 can',   'price' => 30],
                    ['name' => 'Oyster sauce',            'qty' => '2 tbsp',  'price' => 15],
                    ['name' => 'Chicken broth',           'qty' => '½ cup',   'price' => 8],
                    ['name' => 'Cornstarch',              'qty' => '1 tbsp',  'price' => 5],
                ],
            ],
            [
                'title'       => 'Lito\'s Fried Rice Special',
                'description' => 'My go-to sinangag recipe using leftover rice — garlic-heavy and loaded with toppings.',
                'budget_tag'  => 'budget_100',
                'cost'        => 85,
                'servings'    => 2,
                'prep'        => 5,
                'cook'        => 10,
                'difficulty'  => 'easy',
                'source'      => 'community',
                'published'   => false,
                'tags'        => ['itlog', 'mabilis', 'espesyal'],
                'steps'       => [
                    'Crush garlic with the flat of a knife — lots of garlic!',
                    'Fry garlic in plenty of oil until golden brown. Set aside.',
                    'In the same pan, scramble eggs halfway then push to the side.',
                    'Add cold leftover rice and stir-fry on high heat for 3 minutes.',
                    'Season with soy sauce and white pepper. Top with garlic chips and spring onion.',
                ],
                'ingredients' => [
                    ['name' => 'Cold cooked rice',   'qty' => '2 cups',    'price' => 20],
                    ['name' => 'Garlic',             'qty' => '8 cloves',  'price' => 10],
                    ['name' => 'Eggs',               'qty' => '2 pcs',     'price' => 16],
                    ['name' => 'Soy sauce',          'qty' => '1 tbsp',    'price' => 3],
                    ['name' => 'White pepper',       'qty' => 'pinch',     'price' => 2],
                    ['name' => 'Spring onion',       'qty' => '2 stalks',  'price' => 8],
                    ['name' => 'Cooking oil',        'qty' => '3 tbsp',    'price' => 8],
                ],
            ],
        ];

        foreach ($recipes as $data) {
            $recipe = Recipe::create([
                'user_id'           => $user->id,
                'title'             => $data['title'],
                'description'       => $data['description'],
                'source'            => $data['source'],
                'budget_tag'        => $data['budget_tag'],
                'estimated_cost'    => $data['cost'],
                'servings'          => $data['servings'],
                'prep_time_minutes' => $data['prep'],
                'cook_time_minutes' => $data['cook'],
                'difficulty'        => $data['difficulty'],
                'tags'              => $data['tags'],
                'steps'             => $data['steps'],
                'is_published'      => $data['published'],
                'is_premium_only'   => false,
            ]);

            foreach ($data['ingredients'] as $i => $ing) {
                RecipeIngredient::create([
                    'recipe_id'       => $recipe->id,
                    'name'            => $ing['name'],
                    'quantity'        => $ing['qty'],
                    'unit'            => '',
                    'estimated_price' => $ing['price'],
                    'sort_order'      => $i,
                ]);
            }
        }

        $this->command->info("Seeded 10 recipes for user: {$user->name} ({$user->username}).");
    }
}
