/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTindahanIndexRouteImport } from './routes/_authenticated/tindahan/index'
import { Route as AuthenticatedTindahanCommentsIndexRouteImport } from './routes/_authenticated/tindahan-comments/index'
import { Route as AuthenticatedTechnicalIndexRouteImport } from './routes/_authenticated/technical/index'
import { Route as AuthenticatedSupportTicketsIndexRouteImport } from './routes/_authenticated/support-tickets/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSellerSubscriptionsIndexRouteImport } from './routes/_authenticated/seller-subscriptions/index'
import { Route as AuthenticatedRecipesIndexRouteImport } from './routes/_authenticated/recipes/index'
import { Route as AuthenticatedPostsIndexRouteImport } from './routes/_authenticated/posts/index'
import { Route as AuthenticatedPaymentsIndexRouteImport } from './routes/_authenticated/payments/index'
import { Route as AuthenticatedMonetizationIndexRouteImport } from './routes/_authenticated/monetization/index'
import { Route as AuthenticatedMarketsIndexRouteImport } from './routes/_authenticated/markets/index'
import { Route as AuthenticatedMarketPricesIndexRouteImport } from './routes/_authenticated/market-prices/index'
import { Route as AuthenticatedListingReportsIndexRouteImport } from './routes/_authenticated/listing-reports/index'
import { Route as AuthenticatedLegalIndexRouteImport } from './routes/_authenticated/legal/index'
import { Route as AuthenticatedGovernmentPriceReferencesIndexRouteImport } from './routes/_authenticated/government-price-references/index'
import { Route as AuthenticatedFaqsIndexRouteImport } from './routes/_authenticated/faqs/index'
import { Route as AuthenticatedCommunityPriceReportsIndexRouteImport } from './routes/_authenticated/community-price-reports/index'
import { Route as AuthenticatedCommentsIndexRouteImport } from './routes/_authenticated/comments/index'
import { Route as AuthenticatedBoostsIndexRouteImport } from './routes/_authenticated/boosts/index'
import { Route as AuthenticatedSettingsSecurityRouteImport } from './routes/_authenticated/settings/security'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTindahanIndexRoute =
  AuthenticatedTindahanIndexRouteImport.update({
    id: '/tindahan/',
    path: '/tindahan/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTindahanCommentsIndexRoute =
  AuthenticatedTindahanCommentsIndexRouteImport.update({
    id: '/tindahan-comments/',
    path: '/tindahan-comments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTechnicalIndexRoute =
  AuthenticatedTechnicalIndexRouteImport.update({
    id: '/technical/',
    path: '/technical/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportTicketsIndexRoute =
  AuthenticatedSupportTicketsIndexRouteImport.update({
    id: '/support-tickets/',
    path: '/support-tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSellerSubscriptionsIndexRoute =
  AuthenticatedSellerSubscriptionsIndexRouteImport.update({
    id: '/seller-subscriptions/',
    path: '/seller-subscriptions/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRecipesIndexRoute =
  AuthenticatedRecipesIndexRouteImport.update({
    id: '/recipes/',
    path: '/recipes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPostsIndexRoute = AuthenticatedPostsIndexRouteImport.update({
  id: '/posts/',
  path: '/posts/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsIndexRoute =
  AuthenticatedPaymentsIndexRouteImport.update({
    id: '/payments/',
    path: '/payments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMonetizationIndexRoute =
  AuthenticatedMonetizationIndexRouteImport.update({
    id: '/monetization/',
    path: '/monetization/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketsIndexRoute =
  AuthenticatedMarketsIndexRouteImport.update({
    id: '/markets/',
    path: '/markets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketPricesIndexRoute =
  AuthenticatedMarketPricesIndexRouteImport.update({
    id: '/market-prices/',
    path: '/market-prices/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedListingReportsIndexRoute =
  AuthenticatedListingReportsIndexRouteImport.update({
    id: '/listing-reports/',
    path: '/listing-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLegalIndexRoute = AuthenticatedLegalIndexRouteImport.update({
  id: '/legal/',
  path: '/legal/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGovernmentPriceReferencesIndexRoute =
  AuthenticatedGovernmentPriceReferencesIndexRouteImport.update({
    id: '/government-price-references/',
    path: '/government-price-references/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFaqsIndexRoute = AuthenticatedFaqsIndexRouteImport.update({
  id: '/faqs/',
  path: '/faqs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityPriceReportsIndexRoute =
  AuthenticatedCommunityPriceReportsIndexRouteImport.update({
    id: '/community-price-reports/',
    path: '/community-price-reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCommentsIndexRoute =
  AuthenticatedCommentsIndexRouteImport.update({
    id: '/comments/',
    path: '/comments/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBoostsIndexRoute =
  AuthenticatedBoostsIndexRouteImport.update({
    id: '/boosts/',
    path: '/boosts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsSecurityRoute =
  AuthenticatedSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/boosts/': typeof AuthenticatedBoostsIndexRoute
  '/comments/': typeof AuthenticatedCommentsIndexRoute
  '/community-price-reports/': typeof AuthenticatedCommunityPriceReportsIndexRoute
  '/faqs/': typeof AuthenticatedFaqsIndexRoute
  '/government-price-references/': typeof AuthenticatedGovernmentPriceReferencesIndexRoute
  '/legal/': typeof AuthenticatedLegalIndexRoute
  '/listing-reports/': typeof AuthenticatedListingReportsIndexRoute
  '/market-prices/': typeof AuthenticatedMarketPricesIndexRoute
  '/markets/': typeof AuthenticatedMarketsIndexRoute
  '/monetization/': typeof AuthenticatedMonetizationIndexRoute
  '/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/posts/': typeof AuthenticatedPostsIndexRoute
  '/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/seller-subscriptions/': typeof AuthenticatedSellerSubscriptionsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/support-tickets/': typeof AuthenticatedSupportTicketsIndexRoute
  '/technical/': typeof AuthenticatedTechnicalIndexRoute
  '/tindahan-comments/': typeof AuthenticatedTindahanCommentsIndexRoute
  '/tindahan/': typeof AuthenticatedTindahanIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/boosts': typeof AuthenticatedBoostsIndexRoute
  '/comments': typeof AuthenticatedCommentsIndexRoute
  '/community-price-reports': typeof AuthenticatedCommunityPriceReportsIndexRoute
  '/faqs': typeof AuthenticatedFaqsIndexRoute
  '/government-price-references': typeof AuthenticatedGovernmentPriceReferencesIndexRoute
  '/legal': typeof AuthenticatedLegalIndexRoute
  '/listing-reports': typeof AuthenticatedListingReportsIndexRoute
  '/market-prices': typeof AuthenticatedMarketPricesIndexRoute
  '/markets': typeof AuthenticatedMarketsIndexRoute
  '/monetization': typeof AuthenticatedMonetizationIndexRoute
  '/payments': typeof AuthenticatedPaymentsIndexRoute
  '/posts': typeof AuthenticatedPostsIndexRoute
  '/recipes': typeof AuthenticatedRecipesIndexRoute
  '/seller-subscriptions': typeof AuthenticatedSellerSubscriptionsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/support-tickets': typeof AuthenticatedSupportTicketsIndexRoute
  '/technical': typeof AuthenticatedTechnicalIndexRoute
  '/tindahan-comments': typeof AuthenticatedTindahanCommentsIndexRoute
  '/tindahan': typeof AuthenticatedTindahanIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/security': typeof AuthenticatedSettingsSecurityRoute
  '/_authenticated/boosts/': typeof AuthenticatedBoostsIndexRoute
  '/_authenticated/comments/': typeof AuthenticatedCommentsIndexRoute
  '/_authenticated/community-price-reports/': typeof AuthenticatedCommunityPriceReportsIndexRoute
  '/_authenticated/faqs/': typeof AuthenticatedFaqsIndexRoute
  '/_authenticated/government-price-references/': typeof AuthenticatedGovernmentPriceReferencesIndexRoute
  '/_authenticated/legal/': typeof AuthenticatedLegalIndexRoute
  '/_authenticated/listing-reports/': typeof AuthenticatedListingReportsIndexRoute
  '/_authenticated/market-prices/': typeof AuthenticatedMarketPricesIndexRoute
  '/_authenticated/markets/': typeof AuthenticatedMarketsIndexRoute
  '/_authenticated/monetization/': typeof AuthenticatedMonetizationIndexRoute
  '/_authenticated/payments/': typeof AuthenticatedPaymentsIndexRoute
  '/_authenticated/posts/': typeof AuthenticatedPostsIndexRoute
  '/_authenticated/recipes/': typeof AuthenticatedRecipesIndexRoute
  '/_authenticated/seller-subscriptions/': typeof AuthenticatedSellerSubscriptionsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/support-tickets/': typeof AuthenticatedSupportTicketsIndexRoute
  '/_authenticated/technical/': typeof AuthenticatedTechnicalIndexRoute
  '/_authenticated/tindahan-comments/': typeof AuthenticatedTindahanCommentsIndexRoute
  '/_authenticated/tindahan/': typeof AuthenticatedTindahanIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/security'
    | '/boosts/'
    | '/comments/'
    | '/community-price-reports/'
    | '/faqs/'
    | '/government-price-references/'
    | '/legal/'
    | '/listing-reports/'
    | '/market-prices/'
    | '/markets/'
    | '/monetization/'
    | '/payments/'
    | '/posts/'
    | '/recipes/'
    | '/seller-subscriptions/'
    | '/settings/'
    | '/support-tickets/'
    | '/technical/'
    | '/tindahan-comments/'
    | '/tindahan/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/security'
    | '/boosts'
    | '/comments'
    | '/community-price-reports'
    | '/faqs'
    | '/government-price-references'
    | '/legal'
    | '/listing-reports'
    | '/market-prices'
    | '/markets'
    | '/monetization'
    | '/payments'
    | '/posts'
    | '/recipes'
    | '/seller-subscriptions'
    | '/settings'
    | '/support-tickets'
    | '/technical'
    | '/tindahan-comments'
    | '/tindahan'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/security'
    | '/_authenticated/boosts/'
    | '/_authenticated/comments/'
    | '/_authenticated/community-price-reports/'
    | '/_authenticated/faqs/'
    | '/_authenticated/government-price-references/'
    | '/_authenticated/legal/'
    | '/_authenticated/listing-reports/'
    | '/_authenticated/market-prices/'
    | '/_authenticated/markets/'
    | '/_authenticated/monetization/'
    | '/_authenticated/payments/'
    | '/_authenticated/posts/'
    | '/_authenticated/recipes/'
    | '/_authenticated/seller-subscriptions/'
    | '/_authenticated/settings/'
    | '/_authenticated/support-tickets/'
    | '/_authenticated/technical/'
    | '/_authenticated/tindahan-comments/'
    | '/_authenticated/tindahan/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tindahan/': {
      id: '/_authenticated/tindahan/'
      path: '/tindahan'
      fullPath: '/tindahan/'
      preLoaderRoute: typeof AuthenticatedTindahanIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tindahan-comments/': {
      id: '/_authenticated/tindahan-comments/'
      path: '/tindahan-comments'
      fullPath: '/tindahan-comments/'
      preLoaderRoute: typeof AuthenticatedTindahanCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/technical/': {
      id: '/_authenticated/technical/'
      path: '/technical'
      fullPath: '/technical/'
      preLoaderRoute: typeof AuthenticatedTechnicalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support-tickets/': {
      id: '/_authenticated/support-tickets/'
      path: '/support-tickets'
      fullPath: '/support-tickets/'
      preLoaderRoute: typeof AuthenticatedSupportTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/seller-subscriptions/': {
      id: '/_authenticated/seller-subscriptions/'
      path: '/seller-subscriptions'
      fullPath: '/seller-subscriptions/'
      preLoaderRoute: typeof AuthenticatedSellerSubscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/recipes/': {
      id: '/_authenticated/recipes/'
      path: '/recipes'
      fullPath: '/recipes/'
      preLoaderRoute: typeof AuthenticatedRecipesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/posts/': {
      id: '/_authenticated/posts/'
      path: '/posts'
      fullPath: '/posts/'
      preLoaderRoute: typeof AuthenticatedPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments/': {
      id: '/_authenticated/payments/'
      path: '/payments'
      fullPath: '/payments/'
      preLoaderRoute: typeof AuthenticatedPaymentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monetization/': {
      id: '/_authenticated/monetization/'
      path: '/monetization'
      fullPath: '/monetization/'
      preLoaderRoute: typeof AuthenticatedMonetizationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/markets/': {
      id: '/_authenticated/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof AuthenticatedMarketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/market-prices/': {
      id: '/_authenticated/market-prices/'
      path: '/market-prices'
      fullPath: '/market-prices/'
      preLoaderRoute: typeof AuthenticatedMarketPricesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listing-reports/': {
      id: '/_authenticated/listing-reports/'
      path: '/listing-reports'
      fullPath: '/listing-reports/'
      preLoaderRoute: typeof AuthenticatedListingReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/legal/': {
      id: '/_authenticated/legal/'
      path: '/legal'
      fullPath: '/legal/'
      preLoaderRoute: typeof AuthenticatedLegalIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/government-price-references/': {
      id: '/_authenticated/government-price-references/'
      path: '/government-price-references'
      fullPath: '/government-price-references/'
      preLoaderRoute: typeof AuthenticatedGovernmentPriceReferencesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faqs/': {
      id: '/_authenticated/faqs/'
      path: '/faqs'
      fullPath: '/faqs/'
      preLoaderRoute: typeof AuthenticatedFaqsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community-price-reports/': {
      id: '/_authenticated/community-price-reports/'
      path: '/community-price-reports'
      fullPath: '/community-price-reports/'
      preLoaderRoute: typeof AuthenticatedCommunityPriceReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/comments/': {
      id: '/_authenticated/comments/'
      path: '/comments'
      fullPath: '/comments/'
      preLoaderRoute: typeof AuthenticatedCommentsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/boosts/': {
      id: '/_authenticated/boosts/'
      path: '/boosts'
      fullPath: '/boosts/'
      preLoaderRoute: typeof AuthenticatedBoostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/security': {
      id: '/_authenticated/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthenticatedSettingsSecurityRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsSecurityRoute: typeof AuthenticatedSettingsSecurityRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsSecurityRoute: AuthenticatedSettingsSecurityRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBoostsIndexRoute: typeof AuthenticatedBoostsIndexRoute
  AuthenticatedCommentsIndexRoute: typeof AuthenticatedCommentsIndexRoute
  AuthenticatedCommunityPriceReportsIndexRoute: typeof AuthenticatedCommunityPriceReportsIndexRoute
  AuthenticatedFaqsIndexRoute: typeof AuthenticatedFaqsIndexRoute
  AuthenticatedGovernmentPriceReferencesIndexRoute: typeof AuthenticatedGovernmentPriceReferencesIndexRoute
  AuthenticatedLegalIndexRoute: typeof AuthenticatedLegalIndexRoute
  AuthenticatedListingReportsIndexRoute: typeof AuthenticatedListingReportsIndexRoute
  AuthenticatedMarketPricesIndexRoute: typeof AuthenticatedMarketPricesIndexRoute
  AuthenticatedMarketsIndexRoute: typeof AuthenticatedMarketsIndexRoute
  AuthenticatedMonetizationIndexRoute: typeof AuthenticatedMonetizationIndexRoute
  AuthenticatedPaymentsIndexRoute: typeof AuthenticatedPaymentsIndexRoute
  AuthenticatedPostsIndexRoute: typeof AuthenticatedPostsIndexRoute
  AuthenticatedRecipesIndexRoute: typeof AuthenticatedRecipesIndexRoute
  AuthenticatedSellerSubscriptionsIndexRoute: typeof AuthenticatedSellerSubscriptionsIndexRoute
  AuthenticatedSupportTicketsIndexRoute: typeof AuthenticatedSupportTicketsIndexRoute
  AuthenticatedTechnicalIndexRoute: typeof AuthenticatedTechnicalIndexRoute
  AuthenticatedTindahanCommentsIndexRoute: typeof AuthenticatedTindahanCommentsIndexRoute
  AuthenticatedTindahanIndexRoute: typeof AuthenticatedTindahanIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBoostsIndexRoute: AuthenticatedBoostsIndexRoute,
  AuthenticatedCommentsIndexRoute: AuthenticatedCommentsIndexRoute,
  AuthenticatedCommunityPriceReportsIndexRoute:
    AuthenticatedCommunityPriceReportsIndexRoute,
  AuthenticatedFaqsIndexRoute: AuthenticatedFaqsIndexRoute,
  AuthenticatedGovernmentPriceReferencesIndexRoute:
    AuthenticatedGovernmentPriceReferencesIndexRoute,
  AuthenticatedLegalIndexRoute: AuthenticatedLegalIndexRoute,
  AuthenticatedListingReportsIndexRoute: AuthenticatedListingReportsIndexRoute,
  AuthenticatedMarketPricesIndexRoute: AuthenticatedMarketPricesIndexRoute,
  AuthenticatedMarketsIndexRoute: AuthenticatedMarketsIndexRoute,
  AuthenticatedMonetizationIndexRoute: AuthenticatedMonetizationIndexRoute,
  AuthenticatedPaymentsIndexRoute: AuthenticatedPaymentsIndexRoute,
  AuthenticatedPostsIndexRoute: AuthenticatedPostsIndexRoute,
  AuthenticatedRecipesIndexRoute: AuthenticatedRecipesIndexRoute,
  AuthenticatedSellerSubscriptionsIndexRoute:
    AuthenticatedSellerSubscriptionsIndexRoute,
  AuthenticatedSupportTicketsIndexRoute: AuthenticatedSupportTicketsIndexRoute,
  AuthenticatedTechnicalIndexRoute: AuthenticatedTechnicalIndexRoute,
  AuthenticatedTindahanCommentsIndexRoute:
    AuthenticatedTindahanCommentsIndexRoute,
  AuthenticatedTindahanIndexRoute: AuthenticatedTindahanIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
